language: node_js
node_js:
- node
before_deploy:
- npm run build
deploy:
  provider: npm
  email: anthony.kerz@gmail.com
  api_key:
    secure: fQwskfIVUNxSpd0TPGNPh59rNEDMPK5YfRQO8rSWLzcRGUzH4/rnLH4eC2ylcT0qWw8AfvebSjJgaYz/LHW01M3Sp+ooXmf937PcfQMWvq6EqvfRv9IKzXBU2VkN2C85r1tD5NXwnPQfJXrAzhkS4Ur8xFF8+dPYbgsH+ZuvdbOez7bX6hsLuCZbEv4Pt+knzcGuDaS8lpNK4bmd4pWbwUisFcSF+vyGKqYEOD+N2EvWHbCRUWnJHMs/6sriO6yW5cLXQST7bQMfgnMnb5YPyAgvY3joTn1MbbHdLPplE2kqE5JGfQ4EflFSCeDdp7oWogIyyToP6aEPErdwEvY5nKTQZhkBCwHjDhmmQEeYN2KRrm+8xSqzec/ksMA+znl9ovCu76X8CjJ6kMRDCTsDoBfr0XDWEikdN9/a6jhii7DC3Og96kZ0GADex5AyMxHQaq3m4g13rczY/wUY+zwnansUGtN2TU3nuGl2agsPvhwhBrVVb4I7+pLybXYsmTmshRmBT11sr3LAgl4/ovx74hPkmhx8ifnyOAYlD1p5v1pHMbfhOgZ0N9g9rr4Q98mG5nWhJzae29rxUle9BBB2SmmHSZEae2PZa/CNDDzqdAkc64uLrfxx04GblHuH+D4N40Rchn1vRCJQjZeXuSRhGGKAwuVVE/RGNCvz4hSHU60=
  skip_cleanup: true
  on:
    branch: master
    condition: "-z $TRAVIS_TAG"
